name: Bug Report
description: Please read Wiki before submitting! 
labels: ["bug"]
assignees:
  - corecoding
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please read this form carefully.
  - type: checkboxes
    attributes:
      label: Has this issue been covered in the Wiki?
      description: Please search the Wiki to see if your issue already has a solution.
      options:
      - label: I have read the Wiki and my issue is not covered
        required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue reported already?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true


  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: text
    id: distro
    attributes:
      label: What distribution and version of Linux are you using? 
      description: Ubuntu 21.10, Fedora 35, etc
    validations:
      required: true
