blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/corecoding/Vitals/wiki/
    about: Please read this page submitting a bug report! It will likely save us both time.
