name: Create zip artifact

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Gettext
        run: sudo apt install gettext
#      - uses: papeloto/action-zip@v1
#        with:
#          files: metadata.json extension.js menuItem.js sensors.js values.js prefs.*
#          dest: vitals.zip
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* locale/*.po locale/vitals.pot zip.sh schemas/org.gnome.shell.extensions.vitals.gschema.xml'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
