name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release

#    - name: Debug Output
#      env:
#        BLAH: ${{ secrets.FOOBAR }}
#        REPO_OWNER: corecoding
#      run: echo "Token $BLAH"

    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

#    - name: Zip release folder
#      run: |
#        zip vitals.zip *


#    - name: Bump version and push tag
#      uses: anothrNick/github-tag-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.TOKEN }}
#        REPO_OWNER: corecoding

    - name: Bump version and push tag
      #uses: anothrNick/github-tag-action@1.36.0
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
