name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release

    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

    - name: Grab version from meta data
      run: echo "VERSION=$(jq .version metadata.json)" >> $GITHUB_ENV

    - name: Debug Output
      run: git tag v$VERSION

#    - name: Zip release folder
#      run: |
#        zip vitals.zip *

